### ISSUE TITLE
UnsupportedOperationException: direct buffer on client-side

### ISSUE THREAD

**Issue by DasDarki** [Prokyo/ProkyoNet#76]
Situation:
Server successfully started.
Client wants to connect, connection successfully established.
Server-Connect-Event gets fired. Sending a packet with client related data to the client.
The data could be received and than the following stacktrace occurres. 

Stacktrace:
https://haste.paddsel.de/ufozucebav.php

The internet discusses about the error occurring in the ByteBuf#array method. 
But what the exact problem is, is unclear.

**Comment by Microsamp** [comment]
https://github.com/Prokyo/ProkyoNet/blob/develop/common/src/main/java/de/prokyo/network/common/buffer/PacketBuffer.java#L1241
This is the line, the stacktrace refers to. I'll check nettys docs.

**Comment by Microsamp** [comment]
Ok, I'll just implement a workaround
